# Download needed packages

install.packages("tidyverse")
install.packages("lubridate")
install.packages("readr")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("knitr")
install.packages("tidyverse")
install.packages(kableExtra)
install.packages(patchwork)
install.packages(gridExtra)
install.packages("hts")
install.packages("rmarkdown")
install.packages("Matrix")
install.packages("reshape2")
install.packages("fable")
install.packages("fabletools")
install.packages("tidyverse")
install.packages("tsibble")
